In [132]:
from requests import get
import requests
from bs4 import BeautifulSoup as Soup
import pandas as pd
import json
from tqdm.notebook import tqdm # show progress-bar
import re
import time
#크롬 드라이버를 통한  접속
from selenium.webdriver.chrome.options import Options 

from selenium import webdriver
from selenium.webdriver.common.keys import Keys

# 영화번호, [개인 user Id, 개인 user 평점 ], 영화 제목, 장르

In [133]:
Name = []
Year = []
Rating = []
Meta_score = []
Votes = []
Genre = []
Movie_No = []
Director = []
Star = []
Actor_list = []

User_ID = []
User_rating_movie = []
User_rating = []

In [134]:
movie = pd.read_csv("./Movie_No.csv", index_col=0)

In [135]:
movie

      Movie_No
1      2382320
2      1160419
3      6264654
4      8110232
5      7097896
...        ...
996   13606088
997   13936336
998   13804084
999    9697780
1000   9340916

[1000 rows x 1 columns]

In [136]:
driver = webdriver.Chrome("./driver/chromedriver")
# driver.set_page_load_timeout("20")

In [137]:
for i in tqdm(range(1)):      

    movieId = str(movie["Movie_No"][i+1])
    print(movieId)
    if len(movieId) == 6 :
        url = 'https://www.imdb.com/title/tt' + '0' + movieId + '/reviews?sort=submissionDate&dir=asc&ratingFilter=0'
        driver.get(url) # 영화 페이지
        time.sleep(2)
    else :
        url = 'https://www.imdb.com/title/tt' + movieId + '/reviews?sort=submissionDate&dir=asc&ratingFilter=0'
        driver.get(url) # 영화 페이지
        time.sleep(2)




    try:
        driver.find_element_by_class_name("ipl-load-more__button").send_keys(Keys.ENTER)
        time.sleep(2)
    except Exception as ex:
        print('더이상 "Load More" 없음', ex)
        

    print(" 댓글 수집 ")
    try:
        time.sleep(2)
        soup_data= Soup(driver.page_source, 'html.parser')
        movies_user_name = soup_data.findAll('div', {'class' : 'display-name-date'})
        movies_user_rating = soup_data.findAll('div', {'class' : 'lister-item-content'})

        time.sleep(1)
        
        for i in movies_user_name :
            User_ID.append(i.span.text)
            User_rating_movie.append(movieId)
        
        for i in range(len(movies_user_name)):
            
            try :
                if (movies_user_rating[i].span.text.strip()[-5:-3] == User_ID[i][-5:-3]) :
                    User_rating.append('0')
                else :
                    User_rating.append(movies_user_rating[i].span.text.strip()[-5:-3])
            except Exception as ex :
                print("뭔가 없음")
                print(movies_user_name[i].span.text)
                
    except Exception as ex:
        re=['nothing']
        print("댓글없음")

  0%|          | 0/1 [00:00<?, ?it/s]

1160419
 댓글 수집

In [141]:
data = list(zip(User_ID, User_rating_movie, User_rating))
df = pd.DataFrame(data, columns = ['User_ID', 'User_rating_movie','User_rating'])

In [142]:
pd.set_option('display.max_row', 500)
pd.set_option('display.max_columns', 100)
df

                User_ID User_rating_movie User_rating
0         richard-47302           1160419           9
1          jamesstucker           1160419          10
2             Joejoesan           1160419           8
3    israelalelei-53441           1160419          10
4              jkspdqdw           1160419           0
5       FabledGentleman           1160419           9
6       jyothisnambiyar           1160419          10
7            halbert-04           1160419           9
8            Finfrosk86           1160419           7
9    barthelemy-bauters           1160419          10
10               syffer           1160419           6
11          kaptensturm           1160419          10
12        lucjangrzesik           1160419          10
13          matdelaunay           1160419          10
14             chiaradm           1160419           4
15               kaki33           1160419          10
16       jeremyjochimek           1160419           6
17         Tweetienator           1160419           5
18       francoisprieto           1160419          10
19    shaunvanhaelewijn           1160419           8
20          sackofwhine           1160419           7
21             qkjszhxp           1160419           4
22             Jihad300           1160419           0
23  sitnalta_cas_necros           1160419           8
24              admplcd           1160419          10
25     lone_wolf_fenrir           1160419           6
26             T-Hadley           1160419          10
27       mariemmastouri           1160419          10
28         my-jonsson92           1160419           4
29         c-eriksson82           1160419           9
30           jvanderuit           1160419          10
31              h-klaas           1160419          10
32          felixalcala           1160419           7
33             knbrates           1160419           9
34             Xamalion           1160419          10
35            maxiboehm           1160419          10
36         Brukernavn03           1160419           9
37         kringelan312           1160419           9
38           mortenheit           1160419          10
39             qjonsson           1160419          10
40          epost-20607           1160419           9
41             calspers           1160419           9
42          till_kappus           1160419          10
43     roxtiemann-73056           1160419          10
44             Kassdhal           1160419          10
45       hamzabelahmadi           1160419          10
46         Stanislaus-K           1160419          10
47            legoldeon           1160419          10
48       jannikpeveling           1160419          10
49             aarongnr           1160419          10

In [143]:
df.count

<bound method DataFrame.count of                 User_ID User_rating_movie User_rating
0         richard-47302           1160419           9
1          jamesstucker           1160419          10
2             Joejoesan           1160419           8
3    israelalelei-53441           1160419          10
4              jkspdqdw           1160419           0
5       FabledGentleman           1160419           9
6       jyothisnambiyar           1160419          10
7            halbert-04           1160419           9
8            Finfrosk86           1160419           7
9    barthelemy-bauters           1160419          10
10               syffer           1160419           6
11          kaptensturm           1160419          10
12        lucjangrzesik           1160419          10
13          matdelaunay           1160419          10
14             chiaradm           1160419           4
15               kaki33           1160419          10
16       jeremyjochimek           1160419           6
17         Tweetienator           1160419           5
18       francoisprieto           1160419          10
19    shaunvanhaelewijn           1160419           8
20          sackofwhine           1160419           7
21             qkjszhxp           1160419           4
22             Jihad300           1160419           0
23  sitnalta_cas_necros           1160419           8
24              admplcd           1160419          10
25     lone_wolf_fenrir           1160419           6
26             T-Hadley           1160419          10
27       mariemmastouri           1160419          10
28         my-jonsson92           1160419           4
29         c-eriksson82           1160419           9
30           jvanderuit           1160419          10
31              h-klaas           1160419          10
32          felixalcala           1160419           7
33             knbrates           1160419           9
34             Xamalion           1160419          10
35            maxiboehm           1160419          10
36         Brukernavn03           1160419           9
37         kringelan312           1160419           9
38           mortenheit           1160419          10
39             qjonsson           1160419          10
40          epost-20607           1160419           9
41             calspers           1160419           9
42          till_kappus           1160419          10
43     roxtiemann-73056           1160419          10
44             Kassdhal           1160419          10
45       hamzabelahmadi           1160419          10
46         Stanislaus-K           1160419          10
47            legoldeon           1160419          10
48       jannikpeveling           1160419          10
49             aarongnr           1160419          10>

In [144]:
# 중복 확인
df.duplicated(['User_ID'], keep='first')

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [145]:
len(User_ID)

50

In [146]:
len(User_rating)
# User_rating

50

In [147]:
len(User_rating_movie)

50