In [1]:
from requests import get
from bs4 import BeautifulSoup as Soup
import pandas as pd
from datetime import datetime

In [2]:
Name = []
MovieId = []
Year = []
Rating = []
Meta_score = []
Votes = []
Genre = []
Director = []
Stars = []

In [3]:
Date = datetime.today().strftime("%Y-%m")    # YYYYmmddHHMMSS 형태의 시간 출력

Date

'2021-10'

In [11]:

url = get('https://www.imdb.com/movies-coming-soon/' + Date + '/?ref_=cs_dt_pv')
request = url.text
soup_data = Soup(request, 'html.parser')
movies = soup_data.findAll('div', {'class' : 'list_item odd'})
    
for i in movies:
    # 영화 제목
    Name.append(i.h4.a.text[:-7])
    # 영화 년도
    Year.append(i.h4.a.text[-5:-1])
    # 영화 ID
    MovieId.append(i.h4.a["href"][-8:-1])
    # 영화 장르
    tmp = i.select('p> span')
    tmp = list(filter(lambda x: str(x)[:6] == '<span>', tmp))
    tmp = list(map(lambda x: str(x).replace('<span>','').replace('</span>',''), tmp))
    Genre.append(tmp)
    # 영화 감독
    Director.append(i.find('div', {'class' : 'txt-block'}).span.text.strip())
    # 영화 배우
    
    Stars_ = list(map(lambda x: str(x).replace('</a>',''), i.select('div.txt-block> a')))
    result = []
    for e in Stars_:
        sign = False
        a_result = ''

        for c in e :
            if sign:
                a_result += c

            elif c == '>':
                sign = True
        
        result.append(a_result)

    Stars.append(result)


    # Meta Score
    try :
        Meta_score.append(i.tr.find('div', {'class':'rating_txt'}).span.text.strip())
    except Exception as err:
        print(err)
        Meta_score.append(0)

'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'

In [5]:
Stars

[['Tom Hardy', 'Woody Harrelson', 'Michelle Williams', 'Naomie Harris'],
 ['Alessandro Nivola', 'Leslie Odom Jr.', 'Jon Bernthal', 'Vera Farmiga'],
 ['Vincent Lindon', 'Agathe Rousselle', 'Garance Marillier', 'Laïs Salameh'],
 ['Tim Blake Nelson', 'Scott Haze', 'Gavin Lewis', 'Trace Adkins'],
 ['Daniel Craig', 'Ana de Armas', 'Rami Malek', 'Léa Seydoux'],
 ['Jim Warny', 'Thanet Natisri', 'John Volanthen', 'Derek Anderson'],
 ['Jason Isaacs', 'Martha Plimpton', 'Ann Dowd', 'Reed Birney'],
 ['Jamie Lee Curtis', 'Judy Greer', 'Andi Matichak', 'James Jude Courtney'],
 ['Vicky Krieps', 'Tim Roth', 'Grace Delrue', 'Mia Wasikowska'],
 ['Michael Dorman', 'Sophia Bush', 'Dermot Mulroney', 'RZA'],
 ['J.K. Simmons', 'Kristen Schaal', 'Sharlto Copley', 'Patrick Warburton'],
 ['Timothée Chalamet', 'Rebecca Ferguson', 'Zendaya', 'Oscar Isaac'],
 ['Zach Galifianakis', 'Jack Dylan Grazer', 'Olivia Colman', 'Ed Helms'],
 ['Annabelle Wallis', 'Kylie Bunbury', 'Alice Eve', 'Thomas Jane'],
 ['Keri Russell', 'Jesse Plemons', 'Jeremy T. Thomas', 'Graham Greene'],
 ['Tilda Swinton',
  'Honor Swinton Byrne',
  'James Spencer Ashworth',
  'Alice McMillan']]

In [6]:
data = list(zip(MovieId, Name, Year, Genre, Meta_score, Director,Stars))

In [7]:
df = pd.DataFrame(data, columns = ['MovieId', 'Name', 'Year', 'Genre','Meta_score', 'Director','Stars'])

In [8]:
df

,MovieId,Name,Year,Genre,Meta_score,Director,Stars
0,7097896,베놈 2: 렛 데어 비 카니지,2021,"[Action, Adventure, Sci-Fi, Thriller]",48,Andy Serkis,"[Tom Hardy, Woody Harrelson, Michelle Williams..."
1,8110232,The Many Saints of Newark,2021,"[Crime, Drama]",60,Alan Taylor,"[Alessandro Nivola, Leslie Odom Jr., Jon Bernt..."
2,0944760,Titane,2021,"[Drama, Sci-Fi, Thriller]",73,Julia Ducournau,"[Vincent Lindon, Agathe Rousselle, Garance Mar..."
3,2731980,Old Henry,2021,[Western],69,Potsy Ponciroli,"[Tim Blake Nelson, Scott Haze, Gavin Lewis, Tr..."
4,2382320,007 노 타임 투 다이,2021,"[Action, Adventure, Thriller]",68,Cary Joji Fukunaga,"[Daniel Craig, Ana de Armas, Rami Malek, Léa S..."
5,9098872,The Rescue,2021,"[Documentary, Drama]",0,Jimmy Chin,"[Jim Warny, Thanet Natisri, John Volanthen, De..."
6,1389748,Mass,2021,[Drama],79,Fran Kranz,"[Jason Isaacs, Martha Plimpton, Ann Dowd, Reed..."
7,0665338,할로윈 킬즈,2021,"[Crime, Horror, Thriller]",47,David Gordon Green,"[Jamie Lee Curtis, Judy Greer, Andi Matichak, ..."
8,6910282,베르히만 아일랜드,2021,[Drama],78,Mia Hansen-Løve,"[Vicky Krieps, Tim Roth, Grace Delrue, Mia Was..."
9,8709338,Hard Luck Love Song,2020,"[Drama, Music, Romance, Thriller]",0,Justin Corsbie,"[Michael Dorman, Sophia Bush, Dermot Mulroney,..."
10,8456190,Seal Team,2021,[Animation],0,Greig Cameron,"[J.K. Simmons, Kristen Schaal, Sharlto Copley,..."
11,1160419,듄,2021,"[Action, Adventure, Drama, Sci-Fi]",75,Denis Villeneuve,"[Timothée Chalamet, Rebecca Ferguson, Zendaya,..."
12,7504818,Ron's Gone Wrong,2021,"[Animation, Adventure, Comedy, Family, Sci-Fi]",68,Sarah Smith,"[Zach Galifianakis, Jack Dylan Grazer, Olivia ..."
13,8956324,Warning,2021,"[Sci-Fi, Thriller]",0,Agata Alexander,"[Annabelle Wallis, Kylie Bunbury, Alice Eve, T..."
14,7740510,Antlers,2021,"[Drama, Horror, Mystery]",66,Scott Cooper,"[Keri Russell, Jesse Plemons, Jeremy T. Thomas..."
15,6992978,수베니어: 파트 II,2021,[Drama],98,Joanna Hogg,"[Tilda Swinton, Honor Swinton Byrne, James Spe..."

In [9]:
df['Genre'][0]

['Action', 'Adventure', 'Sci-Fi', 'Thriller']

In [10]:
df[['Stars']]

                                                Stars
0   [Tom Hardy, Woody Harrelson, Michelle Williams...
1   [Alessandro Nivola, Leslie Odom Jr., Jon Bernt...
2   [Vincent Lindon, Agathe Rousselle, Garance Mar...
3   [Tim Blake Nelson, Scott Haze, Gavin Lewis, Tr...
4   [Daniel Craig, Ana de Armas, Rami Malek, Léa S...
5   [Jim Warny, Thanet Natisri, John Volanthen, De...
6   [Jason Isaacs, Martha Plimpton, Ann Dowd, Reed...
7   [Jamie Lee Curtis, Judy Greer, Andi Matichak, ...
8   [Vicky Krieps, Tim Roth, Grace Delrue, Mia Was...
9   [Michael Dorman, Sophia Bush, Dermot Mulroney,...
10  [J.K. Simmons, Kristen Schaal, Sharlto Copley,...
11  [Timothée Chalamet, Rebecca Ferguson, Zendaya,...
12  [Zach Galifianakis, Jack Dylan Grazer, Olivia ...
13  [Annabelle Wallis, Kylie Bunbury, Alice Eve, T...
14  [Keri Russell, Jesse Plemons, Jeremy T. Thomas...
15  [Tilda Swinton, Honor Swinton Byrne, James Spe...