# Alphavantage Intraday
* API for "real time" stock data
* Freeium model - sign up fro free account to get API key
* Can make API calls directly or install the helper library:
pip install alpha_vantage from the command line

#### https://alphavantage.co

### 1. Set up Environment

In [13]:
import pandas as pd
import matplotlib.pyplot as plt
from alpha_vantage.timeseries import TimeSeries

### 2. Store API Key

In [14]:
# replace with your own API key
key = 'B48ELPKMWRBUJCMP'

### 3. Create TimeSeries Object and Make API Call

In [25]:
ts = TimeSeries(key, output_format='pandas')
# data, meta = ts.get_intraday('TSLA', interval='1min', outputsize='full')
# data, meta = ts.get_daily_adjusted(symbol = "SPY", outputsize = 'full')
data, meta = ts.get_monthly_adjusted(symbol = "SPY")

In [31]:
ts[0]

TypeError: 'TimeSeries' object is not subscriptable

### 4. Examine Data

In [16]:
meta

{'1. Information': 'Monthly Adjusted Prices and Volumes',
 '2. Symbol': 'SPY',
 '3. Last Refreshed': '2021-09-27',
 '4. Time Zone': 'US/Eastern'}

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 262 entries, 2021-09-27 to 1999-12-31
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   1. open             262 non-null    float64
 1   2. high             262 non-null    float64
 2   3. low              262 non-null    float64
 3   4. close            262 non-null    float64
 4   5. adjusted close   262 non-null    float64
 5   6. volume           262 non-null    float64
 6   7. dividend amount  262 non-null    float64
dtypes: float64(7)
memory usage: 16.4 KB

In [18]:

data = data[data.index >= '2019-06-30']
data = data[data.index <= '2021-08-31']
data

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount
date,,,,,,,
2021-08-31,440.34,453.070,436.100,451.56,450.1037,1.253428e+09,0.0000
2021-07-30,428.87,441.800,421.970,438.51,437.0958,1.420580e+09,0.0000
2021-06-30,422.57,428.780,414.700,428.06,426.6795,1.281016e+09,1.3759
2021-05-28,419.43,422.815,404.000,420.04,417.3016,1.527034e+09,0.0000
2021-04-30,398.40,420.720,398.180,417.30,414.5795,1.462173e+09,0.0000
2021-03-31,385.59,398.120,371.880,396.33,393.7462,2.401881e+09,1.2778
2021-02-26,373.72,394.170,370.376,380.36,376.6446,1.297510e+09,0.0000
2021-01-29,375.31,385.850,364.820,370.07,366.4551,1.400692e+09,0.0000
2020-12-31,365.57,378.460,362.030,373.88,370.2279,1.342397e+09,1.5800
2020-11-30,330.20,364.380,327.240,362.06,356.9955,1.534448e+09,0.0000
2020-10-30,337.69,354.020,322.600,326.54,321.9724,1.629408e+09,0.0000
2020-09-30,350.21,358.750,319.800,334.89,330.2056,1.815146e+09,1.3392
2020-08-31,328.32,351.300,327.730,349.31,343.0345,1.044799e+09,0.0000
2020-07-31,309.57,327.230,309.070,326.52,320.6539,1.502719e+09,0.0000
2020-06-30,303.62,323.410,296.740,308.36,302.8202,2.347940e+09,1.3662
2020-05-29,285.31,306.840,272.990,304.32,297.5357,1.901783e+09,0.0000
2020-04-30,247.98,294.880,243.900,290.48,284.0042,2.798274e+09,0.0000
2020-03-31,298.21,313.840,218.260,257.75,252.0039,5.888711e+09,1.4056
2020-02-28,323.35,339.080,285.540,296.26,287.8868,2.099672e+09,0.0000
2020-01-31,323.54,332.950,320.360,321.73,312.6369,1.389179e+09,0.0000
2019-12-31,314.59,323.800,307.130,321.86,312.7633,1.281221e+09,1.5700
2019-11-29,304.92,315.480,304.740,314.31,303.9388,1.035047e+09,0.0000
2019-10-31,297.74,304.550,284.820,303.33,293.3212,1.404744e+09,0.0000
2019-09-30,290.57,302.630,289.270,296.77,286.9776,1.322797e+09,1.3836
2019-08-30,297.60,300.870,281.720,292.45,281.4944,2.038348e+09,0.0000
2019-07-31,296.68,302.230,294.330,297.43,286.2878,1.135592e+09,0.0000

In [19]:
data.columns

Index(['1. open', '2. high', '3. low', '4. close', '5. adjusted close',
       '6. volume', '7. dividend amount'],
      dtype='object')

In [20]:
data = data.drop(columns=['7. dividend amount'], axis=1)

In [21]:
data

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume
date,,,,,,
2021-08-31,440.34,453.070,436.100,451.56,450.1037,1.253428e+09
2021-07-30,428.87,441.800,421.970,438.51,437.0958,1.420580e+09
2021-06-30,422.57,428.780,414.700,428.06,426.6795,1.281016e+09
2021-05-28,419.43,422.815,404.000,420.04,417.3016,1.527034e+09
2021-04-30,398.40,420.720,398.180,417.30,414.5795,1.462173e+09
2021-03-31,385.59,398.120,371.880,396.33,393.7462,2.401881e+09
2021-02-26,373.72,394.170,370.376,380.36,376.6446,1.297510e+09
2021-01-29,375.31,385.850,364.820,370.07,366.4551,1.400692e+09
2020-12-31,365.57,378.460,362.030,373.88,370.2279,1.342397e+09
2020-11-30,330.20,364.380,327.240,362.06,356.9955,1.534448e+09
2020-10-30,337.69,354.020,322.600,326.54,321.9724,1.629408e+09
2020-09-30,350.21,358.750,319.800,334.89,330.2056,1.815146e+09
2020-08-31,328.32,351.300,327.730,349.31,343.0345,1.044799e+09
2020-07-31,309.57,327.230,309.070,326.52,320.6539,1.502719e+09
2020-06-30,303.62,323.410,296.740,308.36,302.8202,2.347940e+09
2020-05-29,285.31,306.840,272.990,304.32,297.5357,1.901783e+09
2020-04-30,247.98,294.880,243.900,290.48,284.0042,2.798274e+09
2020-03-31,298.21,313.840,218.260,257.75,252.0039,5.888711e+09
2020-02-28,323.35,339.080,285.540,296.26,287.8868,2.099672e+09
2020-01-31,323.54,332.950,320.360,321.73,312.6369,1.389179e+09
2019-12-31,314.59,323.800,307.130,321.86,312.7633,1.281221e+09
2019-11-29,304.92,315.480,304.740,314.31,303.9388,1.035047e+09
2019-10-31,297.74,304.550,284.820,303.33,293.3212,1.404744e+09
2019-09-30,290.57,302.630,289.270,296.77,286.9776,1.322797e+09
2019-08-30,297.60,300.870,281.720,292.45,281.4944,2.038348e+09
2019-07-31,296.68,302.230,294.330,297.43,286.2878,1.135592e+09

### 5. Rename Columns and Add Separate Date and Time Columns

In [22]:
columns = ['Open', 'High', 'Low', 'Close', 'Adj Close','Volume']
data.columns = columns
data = data[['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']]
# ([('Adj Close', 'TSLA'),
#             (    'Close', 'TSLA'),
#             (     'High', 'TSLA'),
#             (      'Low', 'TSLA'),
#             (     'Open', 'TSLA'),
#             (   'Volume', 'TSLA')],

In [23]:
data[['Adj Close']]

            Adj Close
date
2021-08-31   450.1037
2021-07-30   437.0958
2021-06-30   426.6795
2021-05-28   417.3016
2021-04-30   414.5795
2021-03-31   393.7462
2021-02-26   376.6446
2021-01-29   366.4551
2020-12-31   370.2279
2020-11-30   356.9955
2020-10-30   321.9724
2020-09-30   330.2056
2020-08-31   343.0345
2020-07-31   320.6539
2020-06-30   302.8202
2020-05-29   297.5357
2020-04-30   284.0042
2020-03-31   252.0039
2020-02-28   287.8868
2020-01-31   312.6369
2019-12-31   312.7633
2019-11-29   303.9388
2019-10-31   293.3212
2019-09-30   286.9776
2019-08-30   281.4944
2019-07-31   286.2878

In [24]:
data['Adj Close'].to_csv('./SPY.csv')