In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

    서울시 고령자 통계현황
    데이터 출처 : https://data.seoul.go.kr/dataList/10020/S/2/datasetView.do

In [3]:
Elder = pd.read_csv("/Users/ds/Elder.txt",delimiter = '\t')

In [4]:
Elder

,기간,자치구,동,전체인구,전체인구.1,전체인구.2,65세이상 인구,65세이상 인구.1,65세이상 인구.2,65세이상 인구.3,65세이상 인구.4,65세이상 인구.5,65세이상 인구.6,65세이상 인구.7,65세이상 인구.8
0,기간,자치구,동,전체인구,전체인구,전체인구,합계,합계,합계,내국인,내국인,내국인,외국인,외국인,외국인
1,기간,자치구,동,계,남자,여자,계,남자,여자,계,남자,여자,계,남자,여자
2,2021.2/4,합계,합계,"9,795,426","4,756,178","5,039,248","1,576,971","698,990","877,981","1,568,769","694,646","874,123","8,202","4,344","3,858"
3,2021.2/4,종로구,소계,"155,106","75,009","80,097","27,605","12,334","15,271","27,386","12,206","15,180",219,128,91
4,2021.2/4,종로구,사직동,"9,636","4,380","5,256","1,761",771,990,"1,740",758,982,21,13,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,2021.2/4,강동구,둔촌1동,145,82,63,35,23,12,34,22,12,1,1,-
449,2021.2/4,강동구,둔촌2동,"25,103","12,359","12,744","4,075","1,854","2,221","4,070","1,853","2,217",5,1,4
450,2021.2/4,강동구,암사1동,"35,118","17,408","17,710","5,971","2,610","3,361","5,957","2,603","3,354",14,7,7
451,2021.2/4,강동구,천호2동,"33,940","16,717","17,223","5,874","2,664","3,210","5,848","2,651","3,197",26,13,13
452,2021.2/4,강동구,길동,"46,338","22,586","23,752","7,749","3,551","4,198","7,744","3,550","4,194",5,1,4

In [ ]:
# 자료는 잘 정리 되어 있는 것 같다.
# 고령자의 비율을 어디까지로 정의 할 것인지를 토의해야 할 것같다. 
# 그리고 고령자의 비율 대신 경제 활동인구를 기준으로 하는 것도 괜찮을 것 같다.