In [26]:
import pandas as pd
import numpy as np

In [27]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [32]:
# cctv 데이터 읽어오기
# 판다스의 read_csv('경로를 포함한 파일명',encoding=' 인코딩명')
# 데이터에 한글이 포함되어 있는 경우 : 인코딩 방식을 설정

real_estate = pd.read_csv('./서울특별시_부동산_실거래가_정보_2018년.csv', encoding='euc-kr')

real_estate.head() # df의 첫 5행

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,실거래가아이디,지번코드,시군구코드,자치구명,법정동코드,법정동명,신고년도,업무구분코드,업무구분,물건번호,대지권면적,건물면적,관리구분코드,층정보,건물주용도코드,건물주용도,물건금액,건축년도,건물명
0,11710-2018-4-0006022-1,1171011300101360000,11710,송파구,1171011300,거여동,2018,4,신고,1,NaN,59.79,0,2.0,2001,아파트,410000000,1999.0,삼호
1,11350-2018-4-0003763-1,1135010200109290000,11350,노원구,1135010200,월계동,2018,4,신고,1,NaN,59.95,0,14.0,2001,아파트,360000000,2000.0,현대
2,11350-2018-4-0003764-1,1135010600103640012,11350,노원구,1135010600,중계동,2018,4,신고,1,NaN,44.10,0,8.0,2001,아파트,255000000,1993.0,주공6
3,11350-2018-4-0003765-1,1135010200109290000,11350,노원구,1135010200,월계동,2018,4,신고,1,NaN,59.95,0,4.0,2001,아파트,370000000,2000.0,현대
4,11350-2018-4-0003830-1,1135010300103790002,11350,노원구,1135010300,공릉동,2018,4,신고,1,NaN,74.97,0,3.0,2001,아파트,250000000,2003.0,엘림타운