In [1]:
import pandas as pd

In [2]:
Emotion = pd.read_csv('./after_csv/EmoByMovie.csv')

In [4]:
Emotion

     imdb_movie_Id  Happy  Angry  Surprise   Sad  Fear
0           172495   0.15   0.04      0.34  0.18  0.26
1           241527   0.16   0.05      0.29  0.18  0.32
2           246460   0.12   0.06      0.20  0.19  0.43
3           266308   0.15   0.05      0.26  0.21  0.33
4           279113   0.15   0.06      0.24  0.25  0.30
..             ...    ...    ...       ...   ...   ...
102       13056008   0.18   0.04      0.30  0.19  0.29
103       13069986   0.14   0.06      0.24  0.29  0.26
104       13372884   0.18   0.05      0.20  0.23  0.31
105       14700948   0.39   0.02      0.36  0.14  0.09
106       14867006   0.14   0.05      0.29  0.25  0.27

[107 rows x 6 columns]

In [6]:
Emotion = Emotion.set_index('imdb_movie_Id')

In [8]:
Emotion.to_csv('./After_csv/Emotion.csv')