In [1]:
import pandas as pd

In [3]:
movies = pd.read_csv('./after_csv/movies.csv')

In [12]:
movies.loc['10993'] = [11465692, 'C.I.Ape', '["Comedy","Faimly"]', 'Ali Zamani', 'Stephen Johnston']

In [13]:
movies.to_csv('./after_csv/movies.csv')

In [15]:
movies

,imdb_movie_Id,title,genres,Director_name,Actor_name
0,114709,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,NaN,NaN
1,113497,Jumanji (1995),Adventure|Children|Fantasy,NaN,NaN
2,113228,Grumpier Old Men (1995),Comedy|Romance,NaN,NaN
3,114885,Waiting to Exhale (1995),Comedy|Drama|Romance,NaN,NaN
4,113041,Father of the Bride Part II (1995),Comedy,NaN,NaN
...,...,...,...,...,...
10989,4033502,배드 럭 뱅잉,"['Comedy', 'Drama']",Radu Jude,"['Katia Pascariu', 'Claudia Ieremia', 'Olimpia..."
10990,1271038,Licorice Pizza,"['Comedy', 'Drama']",Paul Thomas Anderson,"['Bradley Cooper', 'Skyler Gisondo', 'Sean Pen..."
10991,6920084,Resident Evil: Welcome to Raccoon City,"['Action', 'Horror', 'Mystery', 'Sci-Fi']",Johannes Roberts,"['Kaya Scodelario', 'Robbie Amell', 'Hannah Jo..."
10992,4547524,National Champions,['Drama'],Ric Roman Waugh,"['Alexander Ludwig', 'Timothy Olyphant', 'J.K...."
10993,11465692,C.I.Ape,"[""Comedy"",""Faimly""]",Ali Zamani,Stephen Johnston

In [17]:
ratings = pd.read_csv('./after_csv/ratings.csv')

In [18]:
ratings

,Unnamed: 0,imdb_movie_Id,title,genres,Director_name,Actor_name
0,0,114709,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,NaN,NaN
1,1,113497,Jumanji (1995),Adventure|Children|Fantasy,NaN,NaN
2,2,113228,Grumpier Old Men (1995),Comedy|Romance,NaN,NaN
3,3,114885,Waiting to Exhale (1995),Comedy|Drama|Romance,NaN,NaN
4,4,113041,Father of the Bride Part II (1995),Comedy,NaN,NaN
...,...,...,...,...,...,...
10989,10989,4033502,배드 럭 뱅잉,"['Comedy', 'Drama']",Radu Jude,"['Katia Pascariu', 'Claudia Ieremia', 'Olimpia..."
10990,10990,1271038,Licorice Pizza,"['Comedy', 'Drama']",Paul Thomas Anderson,"['Bradley Cooper', 'Skyler Gisondo', 'Sean Pen..."
10991,10991,6920084,Resident Evil: Welcome to Raccoon City,"['Action', 'Horror', 'Mystery', 'Sci-Fi']",Johannes Roberts,"['Kaya Scodelario', 'Robbie Amell', 'Hannah Jo..."
10992,10992,4547524,National Champions,['Drama'],Ric Roman Waugh,"['Alexander Ludwig', 'Timothy Olyphant', 'J.K...."
10993,10993,11465692,C.I.Ape,"[""Comedy"",""Faimly""]",Ali Zamani,Stephen Johnston