In [5]:
# 팀원들의 피드백을 참고하여 
# 1. 날짜 칼럼, 평당 가격, 국민 평수 가격을 추가하여 작업하였다
# 2. 수작업을 반복하지 않기 위해 동적 변수를 이용하는 것에 초점을 두고 다시 작업하였다.

In [6]:
# 필요한 모듈 임포트
import numpy as np # 선형대수 
import pandas as pd # 데이터 프레임
%matplotlib inline 
# 그래프 쥬피터 노트북 위에 그려지게끔 
import seaborn as sns # 데이터 시각화 
import matplotlib.pyplot as plt # 데이터 시각화

    데이터 출처 : https://rt.molit.go.kr
    기간 : 2017년 01월 01일 ~ 2020년 12월 31일
    범위 : 서울시 아파트 계약일을 기준으로 한 아파트 매매 거래 금액

### read_csv 하는데 필요한 파일 목록

- ./data/2017아파트실거래가.csv
- ./data/2018아파트실거래가.csv
- ./data/2019아파트실거래가.csv
- ./data/2020아파트실거래가.csv

In [3]:
apart17 = pd.read_csv("./data/2017아파트실거래가.csv", encoding='CP949')
apart18 = pd.read_csv("./data/2018아파트실거래가.csv", encoding='CP949')
apart19 = pd.read_csv("./data/2019아파트실거래가.csv", encoding='CP949')
apart20 = pd.read_csv("./data/2020아파트실거래가.csv", encoding='CP949')

In [8]:
pd.concat([apart17,apart18,apart19,apart20])

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일
0,서울특별시 강남구 개포동,655-2,655.0,2.0,개포2차현대아파트(220),77.75,201703,15,"80,000",7,1988,언주로 103,NaN
1,서울특별시 강남구 개포동,655-2,655.0,2.0,개포2차현대아파트(220),77.75,201704,19,"85,000",2,1988,언주로 103,NaN
2,서울특별시 강남구 개포동,655-2,655.0,2.0,개포2차현대아파트(220),77.75,201707,8,"89,900",1,1988,언주로 103,NaN
3,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,201704,13,"97,500",4,1987,언주로 3,NaN
4,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,201704,17,"98,000",1,1987,언주로 3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
84221,서울특별시 중랑구 중화동,274-77,274.0,77.0,한영(104),67.57,202008,7,"26,000",2,2003,동일로144길 74,NaN
84222,서울특별시 중랑구 중화동,11,11.0,0.0,현대휴앤미,95.94,202007,10,"44,000",6,2007,봉화산로27가길 23,NaN
84223,서울특별시 중랑구 중화동,11,11.0,0.0,현대휴앤미,100.17,202012,3,"54,800",5,2007,봉화산로27가길 23,NaN
84224,서울특별시 중랑구 중화동,11-7,11.0,7.0,현대휴앤미(102동),77.71,202009,28,"40,000",5,2007,봉화산로27가길 19,NaN
84225,서울특별시 중랑구 중화동,11-7,11.0,7.0,현대휴앤미(102동),77.71,202009,28,"40,000",5,2007,봉화산로27가길 19,20201027.0

In [4]:
# 구 명을 데이터 프레임으로 만들때 사용하기 위해 따로 리스트를 작성해두었다. 
seoul_gu=["노원구",
"송파구",
"강서구",
"강남구",
"강동구",
"구로구",
"성북구",
"양천구",
"도봉구",
"서초구",
"영등포구",
"성동구",
"동대문구",
"마포구",
"동작구",
"은평구",
"중랑구",
"관악구",
"서대문구",
"강북구",
"용산구",
"광진구",
"금천구",
"중구",
"종로구",]

In [23]:
for i in range(17,21):
    # 주택 평균 가격을 담을 리스트를 추가하였다. 
    globals()['medv'+str(i)] = []
    # 거래금액이 문자형으로 저장되어있고, 자리수 기호(,) 때문에 정수형으로 바꿔지지 않아서 자리수 기호르 삭제해주었다.
    globals()['apart'+str(i)]["거래금액(만원)"]=globals()['apart'+str(i)]["거래금액(만원)"].str.replace(pat=r'[^\w]', repl=r'', regex=True)
    globals()['apart'+str(i)]["거래금액(만원)"].head(3)
    # 거래금액을 수치형으로 변환해주었다.
    globals()['apart'+str(i)]["거래금액(만원)"]=globals()['apart'+str(i)]["거래금액(만원)"].astype("float")
    globals()['apart'+str(i)]["거래금액(만원)"].head(3)
    # 구 별 자료를 쓰기 위해서 주소를 기준으로 시,구,동으로 나누어주었다. (이 부분도 원래는 "군"을 고치지 않았는데 더 정확한 정보를 표기 하도록 수정)
    globals()['apart'+str(i)][['시','구','동']] = globals()['apart'+str(i)].시군구.str.split(" ",expand=True)
    globals()['apart'+str(i)]["거래금액(만원)/전용면적(㎡)"]=globals()['apart'+str(i)]["거래금액(만원)"]/globals()['apart'+str(i)]["전용면적(㎡)"]

    for gu in seoul_gu:
        globals()['medv'+str(i)].append(globals()['apart'+str(i)][globals()['apart'+str(i)]["구"]==gu]["거래금액(만원)/전용면적(㎡)"].mean())
    globals()['df'+str(i)]=pd.DataFrame([seoul_gu,globals()['medv'+str(i)]]).T
    globals()['df'+str(i)].columns=["구","거래금액(만원)/전용면적(㎡)"]
    # 자료를 처음 보는 사람들도 년도를 빨리 파악할 수 있게 날짜를 추가해달라는 피드백을 참고하여 날짜 칼럼을 추가하였다(great)
    globals()['df'+str(i)]["년도"]="20"+str(i)
    # 1평은 약 3.3 제곱이므로 3.3을 곱하여 1평당 아파트 평균 가격을 나타내줄 칼럼을 추가하였다. 
    globals()['df'+str(i)]["거래금액(만원)/1평"]=globals()['df'+str(i)]["거래금액(만원)/전용면적(㎡)"]*3.305785
    # 많이 쓰이는 국민 평수인 32평당 아파트 평균 가격을 나타내줄 칼럼을 추가하였다. 
    globals()['df'+str(i)]["거래금액(만원)/국민평수(32평)"]=globals()['df'+str(i)]["거래금액(만원)/전용면적(㎡)"]*3.305785*32
    globals()['df'+str(i)]=globals()['df'+str(i)][["구","년도", "거래금액(만원)/전용면적(㎡)", "거래금액(만원)/1평", "거래금액(만원)/국민평수(32평)"]]
    globals()['df'+str(i)].sort_values(by="구", ascending=True, inplace=True)
    globals()['df'+str(i)].reset_index(drop=True,inplace=True)
    globals()['df'+str(i)].to_csv('./fin_data/20'+str(i)+'년도_서울시_아파트_평균금액.csv',header=True,index=False)

In [28]:
globals()['df'+str(17)].head(24)

       구    년도 거래금액(만원)/전용면적(㎡)  거래금액(만원)/1평 거래금액(만원)/국민평수(32평)
0    강남구  2017      1466.082319   4846.55294      155089.694095
1    강동구  2017       746.577889  2468.025987       78976.831588
2    강북구  2017       514.432978  1700.604821       54419.354283
3    강서구  2017       652.271984   2156.27094       69000.670094
4    관악구  2017       572.530041  1892.661221       60565.159083
5    광진구  2017       791.122427  2615.280651       83688.980847
6    구로구  2017       543.784605  1797.634991       57524.319719
7    금천구  2017        473.82271  1566.356007       50123.392225
8    노원구  2017       541.109122   1788.79042       57241.293435
9    도봉구  2017       468.883099  1550.026715       49600.854875
10  동대문구  2017        610.60856   2018.54062       64593.299827
11   동작구  2017       746.293611  2467.086225       78946.759207
12   마포구  2017       835.282045  2761.262855       88360.411357
13  서대문구  2017       662.287611   2189.38045       70060.174404
14   서초구  2017      1238.216487   4093.27749      130984.879668
15   성동구  2017        829.17523  2741.075037       87714.401173
16   성북구  2017       576.890196  1907.074955       61026.398576
17   송파구  2017      1029.914524  3404.675984      108949.631484
18   양천구  2017       777.996203  2571.888178       82300.421711
19  영등포구  2017       717.650612  2372.398628       75916.756094
20   용산구  2017      1012.640605  3347.572122      107122.307909
21   은평구  2017       562.801131  1860.499536        59535.98514
22   종로구  2017       696.595057  2302.793491       73689.391721
23    중구  2017       761.221529  2516.434712       80525.910799

In [29]:
globals()['df'+str(18)].head(24)

       구    년도 거래금액(만원)/전용면적(㎡)  거래금액(만원)/1평 거래금액(만원)/국민평수(32평)
0    강남구  2018      1702.489273  5628.063501      180098.032036
1    강동구  2018        858.38293  2837.629413       90804.141206
2    강북구  2018       563.439324  1862.609267       59603.496538
3    강서구  2018       728.963344  2409.796087         77113.4748
4    관악구  2018       642.227679  2123.066629       67938.132121
5    광진구  2018       946.458796  3128.789292      100121.257344
6    구로구  2018        595.38575   1968.21728       62982.952965
7    금천구  2018       516.092104  1706.089535       54594.865106
8    노원구  2018       601.718602   1989.15233       63652.874569
9    도봉구  2018       504.364747  1667.321414       53354.285255
10  동대문구  2018       693.124869  2291.321796       73322.297465
11   동작구  2018        879.35545  2906.960057        93022.72181
12   마포구  2018       989.618066   3271.46456      104686.865907
13  서대문구  2018       727.430863  2404.730036       76951.361142
14   서초구  2018      1461.551061  4831.573574      154610.354381
15   성동구  2018      1048.798631  3467.102782      110947.289032
16   성북구  2018       629.730767  2081.754522       66616.144704
17   송파구  2018      1203.052937  3977.034353      127265.099292
18   양천구  2018       811.359134  2682.178854       85829.723317
19  영등포구  2018       845.079602  2793.651473       89396.847133
20   용산구  2018      1198.845176    3963.1244      126819.980811
21   은평구  2018       627.251341  2073.558074       66353.858364
22   종로구  2018       764.337795  2526.736419       80855.565411
23    중구  2018       871.607187  2881.345965       92203.070869

In [30]:
globals()['df'+str(19)].head(24)

       구    년도 거래금액(만원)/전용면적(㎡)  거래금액(만원)/1평 거래금액(만원)/국민평수(32평)
0    강남구  2019       2052.02343  6783.548274      217073.544761
1    강동구  2019      1007.348562  3330.077765      106562.488492
2    강북구  2019       665.266528  2199.228108       70375.299446
3    강서구  2019       852.656551  2818.699235       90198.375534
4    관악구  2019       757.872395  2505.363197       80171.622301
5    광진구  2019      1105.816014  3655.589991      116978.879698
6    구로구  2019       707.525475  2338.927102       74845.667251
7    금천구  2019       619.219678  2047.007125       65504.227989
8    노원구  2019       703.655676   2326.13438       74436.300162
9    도봉구  2019       594.083156  1963.911186       62845.157942
10  동대문구  2019         841.1038  2780.508326        88976.26644
11   동작구  2019      1066.528036  3525.712383      112822.796243
12   마포구  2019      1222.074699   4039.91621      129277.318706
13  서대문구  2019       922.649596  3050.081194       97602.598223
14   서초구  2019      1755.428375  5803.068792      185698.201343
15   성동구  2019      1245.322732  4116.769206      131736.614594
16   성북구  2019       771.371885  2549.989607        81599.66741
17   송파구  2019      1440.660535  4762.513985      152400.447532
18   양천구  2019      1038.167409  3431.958249      109822.663961
19  영등포구  2019      1039.327174  3435.792183       109945.34986
20   용산구  2019      1463.556994  4838.204758      154822.552253
21   은평구  2019       729.631737  2412.005651       77184.180848
22   종로구  2019      1015.949523  3358.510694      107472.342213
23    중구  2019      1024.525799   3386.86202      108379.584633

In [31]:
globals()['df'+str(20)].head(24)

       구    년도 거래금액(만원)/전용면적(㎡)  거래금액(만원)/1평 거래금액(만원)/국민평수(32평)
0    강남구  2020      2086.827856  6898.604225      220755.335188
1    강동구  2020      1169.990642  3867.737514       123767.60045
2    강북구  2020       771.148854  2549.252316       81576.074104
3    강서구  2020       964.740519  3189.224736      102055.191545
4    관악구  2020       871.085534  2879.621491       92147.887713
5    광진구  2020      1291.452455  4269.264155      136616.452956
6    구로구  2020       769.806268  2544.814013       81434.048405
7    금천구  2020       739.462355   2444.50356       78224.113907
8    노원구  2020        843.89686  2789.741581       89271.730578
9    도봉구  2020       675.160371  2231.935026        71421.92082
10  동대문구  2020       995.652113   3291.41182      105325.178226
11   동작구  2020      1230.760079  4068.628209      130196.102701
12   마포구  2020      1344.644399  4445.105284      142243.369097
13  서대문구  2020      1038.870468  3434.282412       109897.03717
14   서초구  2020      1914.609285  6329.286654      202537.172937
15   성동구  2020      1471.158544  4863.333848      155626.683136
16   성북구  2020        914.79966  3024.130993       96772.191766
17   송파구  2020      1601.006686  5292.583888      169362.684412
18   양천구  2020      1143.551786  3780.336339       120970.76286
19  영등포구  2020      1180.242814  3901.628992      124852.127732
20   용산구  2020      1594.030917  5269.523496      168624.751871
21   은평구  2020        827.59809  2735.861353       87547.563284
22   종로구  2020      1034.721886   3420.56809      109458.178888
23    중구  2020      1138.634501  3764.080854      120450.587343