In [2]:
import numpy as np
import pandas as pd

In [3]:
movie = pd.read_csv('./20-01~21-09 Top 1000 평점데이터 수정전.csv', index_col=0)

In [4]:
movie

                 User_ID  User_rating_movie User_rating  UserID
0           adrianbabech            2382320          10   10000
1                 zeki-4            2382320           8   10001
2                  Kaiko            2382320           9   10002
3                eespree            2382320           3   10003
4        magadalwarmayur            2382320           8   10004
...                  ...                ...         ...     ...
35438          lazarillo            9697780          ri   45438
35439           ks-60500            9697780           4   11830
35440  alejandro-bonilla            9697780           7   17404
35441            knjwjsk            9340916           9   45441
35442       patrickgrand            9340916           9   45442

[35443 rows x 4 columns]

In [5]:
movie.drop('User_ID', axis=1, inplace = True)

In [6]:
movie

       User_rating_movie User_rating  UserID
0                2382320          10   10000
1                2382320           8   10001
2                2382320           9   10002
3                2382320           3   10003
4                2382320           8   10004
...                  ...         ...     ...
35438            9697780          ri   45438
35439            9697780           4   11830
35440            9697780           7   17404
35441            9340916           9   45441
35442            9340916           9   45442

[35443 rows x 3 columns]

In [7]:
for i in range(len(movie.User_rating)) :
    if movie.User_rating[i] not in ['0','1','2','3','4','5','6','7','8','9','10'] :
        movie.loc[i,'User_rating'] = '0'
        print(i, movie.User_rating[i])

54 0
72 0
165 0
223 0
225 0
236 0
237 0
262 0
271 0
322 0
323 0
430 0
482 0
544 0
566 0
624 0
827 0
842 0
862 0
1015 0
1081 0
1096 0
1110 0
1167 0
1184 0
1221 0
1246 0
1294 0
1298 0
1331 0
1333 0
1357 0
1411 0
1457 0
1487 0
1529 0
1546 0
1616 0
1649 0
1650 0
1655 0
1658 0
1711 0
1712 0
1720 0
1726 0
1738 0
1745 0
1946 0
1950 0
2131 0
2141 0
2339 0
2490 0
2496 0
2516 0
2555 0
2564 0
2621 0
2679 0
2705 0
2738 0
2788 0
2866 0
2867 0
2876 0
2922 0
3037 0
3057 0
3060 0
3098 0
3159 0
3362 0
3417 0
3419 0
3449 0
3468 0
3476 0
3486 0
3533 0
3546 0
3564 0
3651 0
3675 0
3798 0
3936 0
3961 0
4024 0
4059 0
4082 0
4140 0
4163 0
4211 0
4242 0
4243 0
4271 0
4358 0
4391 0
4453 0
4513 0
4688 0
4798 0
4799 0
4878 0
4920 0
5044 0
5124 0
5169 0
5294 0
5317 0
5441 0
5450 0
5531 0
5564 0
5573 0
5624 0
5639 0
5688 0
5789 0
5795 0
5827 0
5857 0
5858 0
5863 0
5886 0
5899 0
5936 0
5964 0
5993 0
6033 0
6041 0
6076 0
6140 0
6154 0
6183 0
6220 0
6227 0
6254 0
6274 0
6338 0
6549 0
6562 0
6568 0
6668 0
6675 0
6713 0
6732 0
6825 0
6874 0
6891 0
6943 0
6946 0
6961 0
6968 0
6999 0
7089 0
7096 0
7102 0
7123 0
7165 0
7198 0
7238 0
7322 0
7334 0
7349 0
7401 0
7496 0
7569 0
7575 0
7586 0
7625 0
7694 0
7702 0
7772 0
7773 0
7826 0
7943 0
7953 0
7954 0
8048 0
8152 0
8173 0
8177 0
8229 0
8317 0
8352 0
8370 0
8376 0
8446 0
8452 0
8464 0
8470 0
8602 0
8614 0
8835 0
8839 0
8857 0
8978 0
9081 0
9084 0
9093 0
9113 0
9171 0
9205 0
9233 0
9250 0
9276 0
9362 0
9381 0
9389 0
9512 0
9616 0
9739 0
9788 0
9794 0
9838 0
9901 0
9906 0
9914 0
9950 0
10041 0
10069 0
10118 0
10147 0
10151 0
10190 0
10290 0
10324 0
10339 0
10407 0
10410 0
10453 0
10464 0
10480 0
10513 0
10531 0
10534 0
10550 0
10648 0
10671 0
10674 0
10707 0
10726 0
10729 0
10882 0
10893 0
10928 0
10930 0
10943 0
10951 0
10988 0
11008 0
11040 0
11104 0
11162 0
11188 0
11213 0
11265 0
11289 0
11299 0
11301 0
11306 0
11307 0
11350 0
11358 0
11418 0
11430 0
11453 0
11480 0
11484 0
11603 0
11624 0
11774 0
11782 0
11837 0
11878 0
11897 0
11901 0
11927 0
11965 0
11976 0
11984 0
11993 0
12022 0
12029 0
12037 0
12241 0
12280 0
12362 0
12366 0
12469 0
12484 0
12485 0
12520 0
12532 0
12549 0
12573 0
12686 0
12733 0
12746 0
12867 0
12881 0
12912 0
13202 0
13211 0
13225 0
13252 0
13259 0
13267 0
13296 0
13298 0
13320 0
13335 0
13358 0
13396 0
13418 0
13448 0
13457 0
13486 0
13515 0
13533 0
13580 0
13616 0
13627 0
13688 0
13722 0
13773 0
13807 0
13848 0
13942 0
13943 0
13954 0
13988 0
14058 0
14068 0
14172 0
14177 0
14182 0
14305 0
14320 0
14364 0
14367 0
14410 0
14423 0
14495 0
14574 0
14575 0
14579 0
14599 0
14626 0
14656 0
14661 0
14685 0
14720 0
14747 0
14825 0
14846 0
14865 0
14958 0
15140 0
15142 0
15153 0
15170 0
15190 0
15205 0
15211 0
15221 0
15230 0
15238 0
15250 0
15275 0
15336 0
15404 0
15453 0
15506 0
15519 0
15536 0
15562 0
15571 0
15604 0
15648 0
15717 0
15727 0
15731 0
15758 0
15762 0
15763 0
15886 0
15906 0
15957 0
16016 0
16083 0
16109 0
16226 0
16303 0
16358 0
16383 0
16407 0
16486 0
16497 0
16588 0
16646 0
16648 0
16660 0
16716 0
16737 0
16742 0
16752 0
16816 0
16858 0
16861 0
16899 0
16938 0
16987 0
17012 0
17021 0
17066 0
17091 0
17111 0
17140 0
17153 0
17155 0
17159 0
17166 0
17170 0
17199 0
17223 0
17226 0
17272 0
17297 0
17336 0
17364 0
17370 0
17371 0
17378 0
17418 0
17441 0
17500 0
17521 0
17523 0
17561 0
17588 0
17602 0
17622 0
17723 0
17779 0
17856 0
17863 0
17910 0
17950 0
17994 0
18007 0
18027 0
18046 0
18068 0
18071 0
18082 0
18105 0
18139 0
18147 0
18199 0
18205 0
18333 0
18426 0
18429 0
18444 0
18463 0
18593 0
18611 0
18616 0
18679 0
18684 0
18725 0
18754 0
18796 0
18826 0
18877 0
18936 0
18939 0
18942 0
18943 0
18964 0
18980 0
19002 0
19124 0
19125 0
19156 0
19157 0
19201 0
19215 0
19288 0
19318 0
19319 0
19364 0
19416 0
19426 0
19429 0
19435 0
19516 0
19587 0
19614 0
19691 0
19789 0
19902 0
19930 0
19932 0
19960 0
19977 0
20088 0
20094 0
20127 0
20159 0
20170 0
20193 0
20196 0
20200 0
20209 0
20211 0
20214 0
20229 0
20230 0
20341 0
20358 0
20382 0
20407 0
20409 0
20446 0
20505 0
20518 0
20575 0
20647 0
20703 0
20718 0
20789 0
20812 0
20815 0
20825 0
20859 0
20860 0
20910 0
20922 0
20940 0
21053 0
21066 0
21097 0
21101 0
21179 0
21329 0
21336 0
21362 0
21475 0
21498 0
21501 0
21534 0
21538 0
21542 0
21568 0
21579 0
21651 0
21665 0
21682 0
21727 0
21751 0
21777 0
21800 0
21826 0
21849 0
21891 0
21897 0
21956 0
22175 0
22195 0
22239 0
22242 0
22260 0
22263 0
22265 0
22285 0
22288 0
22296 0
22318 0
22322 0
22332 0
22350 0
22467 0
22619 0
22632 0
22636 0
22720 0
22773 0
22818 0
22830 0
22866 0
22882 0
22915 0
22985 0
23020 0
23055 0
23123 0
23153 0
23154 0
23155 0
23156 0
23157 0
23159 0
23161 0
23164 0
23169 0
23206 0
23295 0
23372 0
23433 0
23494 0
23508 0
23527 0
23544 0
23578 0
23607 0
23608 0
23628 0
23725 0
23786 0
23817 0
23944 0
23947 0
23980 0
23984 0
24025 0
24027 0
24029 0
24047 0
24075 0
24095 0
24102 0
24111 0
24159 0
24165 0
24184 0
24230 0
24279 0
24281 0
24291 0
24294 0
24317 0
24362 0
24494 0
24502 0
24544 0
24545 0
24585 0
24609 0
24676 0
24729 0
24731 0
24765 0
24811 0
24872 0
25010 0
25015 0
25031 0
25088 0
25112 0
25185 0
25206 0
25282 0
25298 0
25333 0
25362 0
25403 0
25471 0
25493 0
25521 0
25589 0
25597 0
25647 0
25671 0
25727 0
25735 0
25744 0
25757 0
25773 0
25822 0
25863 0
25872 0
25910 0
25964 0
26049 0
26119 0
26120 0
26124 0
26143 0
26207 0
26238 0
26256 0
26298 0
26336 0
26367 0
26377 0
26588 0
26604 0
26675 0
26745 0
26843 0
26909 0
26923 0
26932 0
26943 0
26946 0
27016 0
27068 0
27220 0
27242 0
27249 0
27266 0
27285 0
27293 0
27372 0
27382 0
27385 0
27396 0
27424 0
27511 0
27532 0
27738 0
27777 0
27971 0
28018 0
28031 0
28201 0
28383 0
28386 0
28401 0
28423 0
28518 0
28521 0
28531 0
28536 0
28601 0
28615 0
28618 0
28647 0
28662 0
28676 0
28767 0
28792 0
28861 0
28917 0
28946 0
28985 0
29025 0
29066 0
29098 0
29121 0
29133 0
29214 0
29289 0
29314 0
29323 0
29332 0
29431 0
29441 0
29530 0
29532 0
29541 0
29595 0
29601 0
29652 0
29671 0
29686 0
29697 0
29787 0
29918 0
30010 0
30035 0
30057 0
30078 0
30095 0
30098 0
30103 0
30232 0
30250 0
30257 0
30364 0
30365 0
30368 0
30443 0
30461 0
30555 0
30599 0
30614 0
30616 0
30624 0
30630 0
30644 0
30661 0
30725 0
30731 0
30741 0
30850 0
30885 0
30893 0
30941 0
30952 0
30959 0
30978 0
31018 0
31045 0
31065 0
31069 0
31112 0
31156 0
31196 0
31209 0
31210 0
31249 0
31289 0
31369 0
31377 0
31378 0
31434 0
31487 0
31625 0
31641 0
31715 0
31806 0
31819 0
31841 0
31848 0
31882 0
31918 0
31920 0
31923 0
31996 0
32055 0
32096 0
32234 0
32252 0
32267 0
32302 0
32337 0
32430 0
32494 0
32498 0
32499 0
32502 0
32556 0
32565 0
32651 0
32678 0
32693 0
32755 0
32948 0
32969 0
33006 0
33046 0
33065 0
33127 0
33161 0
33218 0
33260 0
33323 0
33350 0
33376 0
33391 0
33434 0
33503 0
33554 0
33562 0
33593 0
33614 0
33657 0
33697 0
33731 0
33798 0
33821 0
33833 0
33841 0
33856 0
33929 0
33950 0
33953 0
33980 0
33986 0
34016 0
34209 0
34243 0
34246 0
34268 0
34354 0
34375 0
34538 0
34580 0
34650 0
34651 0
34704 0
34713 0
34716 0
34763 0
34767 0
34782 0
34787 0
34813 0
34837 0
34853 0
34926 0
34930 0
34955 0
34962 0
35019 0
35120 0
35220 0
35229 0
35243 0
35252 0
35256 0
35381 0
35407 0
35435 0
35438 0

In [28]:
movie.to_csv('./20-01~21-09 Top 1000 평점데이터 수정후.csv')